name: sonicear
description: subsonic client

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  path: ^1.6.4
  path_provider: any
  crypto: ^2.1.4
  meta: ^1.1.8
  http: ^0.12.1
  provider: ^4.3.1
  bloc: ^6.1.0
  flutter_bloc: ^6.0.6
  sqflite: ^1.3.1
  just_audio: ^0.5.5
  audio_service: ^0.15.2
  rxdart: ^0.24.1
  uuid: any
  infinite_scroll_pagination: ^2.2.1

  flutter_downloader: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: any

flutter:
  uses-material-design: true

  assets:
    - assets/blank_cover.png
