name: Flutter CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - name: Install dependencies
      run: flutter pub get
    - name: Build Android APKs
      run: flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
    - name: Upload Android APKs
      uses: actions/upload-artifact@master
      with:
        name: android-apks
        path: build/app/outputs/flutter-apk
